### ISSUE TITLE
add auto_minor_version_upgrade parameter

### ISSUE THREAD

**Issue by jeekajoo** [azavea/terraform-aws-postgresql-rds#12]
Hi,

Could you add `auto_minor_version_upgrade` parameter ?
This optional parameter defaults to `yes`.
https://www.terraform.io/docs/providers/aws/r/db_instance.html#auto_minor_version_upgrade

Thanks

**Comment by hectcastro** [comment]
Hey @jeekajoo,

Definitely a welcome enhancement. Please feel free to open a PR with the addition if you can get to it before we do.

**Comment by jeekajoo** [comment]
thanks for merging it
