### ISSUE TITLE
You must specify a MonitoringInterval value other than 0 when you specify a MonitoringRoleARN value

### ISSUE THREAD

**Issue by rbreslow** [azavea/terraform-aws-postgresql-rds#31]
It looks like the default functionality of this module is to specify a value for `monitoring_role_arn` on the `aws_db_instance` resource, and set the `monitoring_interval` to `0`. 

According to this Terraform error I received, the default functionality of this module may be broken:

```bash
Error: Error applying plan:

1 error(s) occurred:

* module.database.aws_db_instance.postgresql: 1 error(s) occurred:

* aws_db_instance.postgresql: Error creating DB Instance: InvalidParameterCombination: You must specify a MonitoringInterval value other than 0 when you specify a MonitoringRoleARN value.
	status code: 400, request id: d996bf5a-c269-4548-87ec-6b3676b7a9aa
```

**Comment by hectcastro** [comment]
Interesting. Pretty sure we tested this case when the feature was added. Either way, I think the goal in a fix would be to try and preserve the ability to set `monitoring_interval = 0`, if possible.
